-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "15")

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = false,
            ignore_opacity = false,
            noise = 0.015,
            passes = 2,
            size = 7,
        },
        dim_around = 0.25,
        dim_strength = 0.2,
        inactive_opacity = 0.9,
        shadow = {
            range = 10,
            render_power = 4,
        },
    },
    general = {
        border_size = 1,
        col = {
            active_border = {
                colors = {"rgba(33ccffee)", "rgba(9141acff)"},
                angle = 45,
            },
            inactive_border = "0xaa595959",
        },
        gaps_in = 8,
        gaps_out = 20,
        hover_icon_on_border = true,
    },
})

-- Bezier curves
hl.curve("almostLinear", { type = "bezier", points = { {0.5, 0.5}, {0.75, 1.0} } })

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 0.7,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 0.5,
    bezier = "almostLinear",
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = true,
})

-- Keybinds
hl.bind("CTRL + ALT + S", hl.dsp.exec_cmd("hyprmod"))
