-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "20")

-- Settings
hl.config({
    decoration = {
        blur = {
            ignore_opacity = false,
            noise = 0.015,
            passes = 2,
            size = 7,
        },
        dim_around = 0.25,
        dim_strength = 0.2,
        inactive_opacity = 0.9,
        shadow = {
            range = 10,
            render_power = 4,
        },
    },
    general = {
        border_size = 2,
        col = {
            active_border = {
                colors = {"rgba(33ccffee)", "rgba(9141acff)"},
                angle = 45,
            },
            inactive_border = "0xff000000",
        },
        gaps_out = 7,
        hover_icon_on_border = false,
    },
})

-- Keybinds
hl.unbind("CTRL + ALT + S")
hl.bind("CTRL + ALT + S", hl.dsp.exec_cmd("hyprmod"))
